version: '3.8'
services:
  postgres:
    image: postgres:15.3-alpine
    container_name: database
    hostname: ${DATABASE_HOST}
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ${PWD}/.data/db/${NODE_ENV}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    hostname: ${APP_HOST}
    ports:
      - ${APP_PORT}:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    command: /opt/startup.${NODE_ENV}.sh
