import { IsDefined, Length } from 'class-validator';
import { IsISO6391 } from 'src/utils/validators/isISO6391.validator';
import { bookConstraints as constraints } from 'src/config/constants/database.constraint_values';

export class CreateLanguageDto {
  // @IsDefined()
  // CHECK: Implement @IsExists() validator or catch error generated by the database?
  // book_id: number;

  @IsDefined()
  @Length(constraints.language.length, constraints.language.length)
  @IsISO6391()
  language: string;
}
