import { IsDefined, MaxLength } from 'class-validator';
import { bookConstraints as constraints } from 'src/config/constants/database.constraint_values';

export class CreateLocationDto {
  @IsDefined()
  @MaxLength(constraints.location.maxLength)
  // CHECK: Implement @IsUnique() validator or catch error generated by the database?
  location: string;
}
