# Generated by Django 5.1.7 on 2025-03-18 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.IntegerField(error_messages={'unique': 'A book with that reference already exists.'}, help_text='The unique book reference number', unique=True, verbose_name='reference')),
                ('isbn', models.CharField(blank=True, help_text='The book ISBN', max_length=13, null=True, verbose_name='ISBN')),
                ('title', models.CharField(help_text='The book title', max_length=255, verbose_name='title')),
                ('slug', models.SlugField(help_text='The book slug (ref-title)', max_length=255, unique=True, verbose_name='slug')),
                ('author', models.CharField(blank=True, help_text='The book author or authors', max_length=255, verbose_name='author')),
                ('publication_place', models.CharField(blank=True, help_text='The book publication place (city or country)', max_length=255, null=True, verbose_name='publication place')),
                ('publisher', models.CharField(blank=True, help_text='The book publisher', max_length=255, null=True, verbose_name='publisher')),
                ('collection', models.CharField(blank=True, help_text='The book collection or series (e.g. Austral of Espasa Calpe)', max_length=255, null=True, verbose_name='collection')),
                ('year', models.IntegerField(blank=True, help_text='The book publication year', null=True, verbose_name='publication year')),
                ('size', models.CharField(blank=True, help_text='The book size (large x width in cm) (e.g. 8cm x 12cm)', max_length=255, null=True, verbose_name='size')),
                ('weight', models.IntegerField(blank=True, help_text='The book weight in grams', null=True, verbose_name='weight')),
                ('pages', models.IntegerField(blank=True, help_text='The book number of pages', null=True, verbose_name='pages')),
                ('condition', models.CharField(blank=True, help_text='The physical book condition (e.g. new, used, etc)', max_length=255, null=True, verbose_name='condition')),
                ('description', models.TextField(blank=True, help_text='The book description', null=True, verbose_name='description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='The book price in euros', max_digits=10, null=True, verbose_name='price')),
                ('stock', models.IntegerField(default=1, help_text='The book stock', verbose_name='stock')),
                ('binding', models.CharField(blank=True, help_text='The book binding (e.g. paperback, hardcover, etc)', max_length=255, null=True, verbose_name='binding')),
                ('private_notes', models.TextField(blank=True, help_text='Private notes about the book', null=True, verbose_name='private notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the book was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the book was last updated', verbose_name='updated at')),
                ('sold_at', models.DateTimeField(blank=True, help_text='The date and time the book was sold', null=True, verbose_name='sold at')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The location name (e.g. Store, Warehouse (shelf 13), etc)', max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='The location description (e.g. Warehouse shelf 13 at the back of the store)', null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The status name (e.g. Sold, Available, etc)', max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='The status description', null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'status',
                'verbose_name_plural': 'statuses',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The image URL', max_length=2000, verbose_name='URL')),
                ('book', models.ForeignKey(help_text='The book the image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='books.book', verbose_name='book')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='The keyword name', max_length=75, unique=True, verbose_name='name')),
                ('book', models.ForeignKey(help_text='The book the keyword belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='books.book', verbose_name='book')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The language code (ISO 639-1 Alpha-2) (e.g. en, es, fr, etc)', max_length=2, unique=True, verbose_name='code')),
                ('books', models.ManyToManyField(help_text='The books related to the language', related_name='languages', to='books.book', verbose_name='books')),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The book location (e.g. Store, Warehouse, etc)', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='books', to='books.location', verbose_name='location'),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.ForeignKey(help_text='The book status', on_delete=django.db.models.deletion.RESTRICT, related_name='books', to='books.status', verbose_name='status'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The topic name (e.g. Science Fiction, Fantasy, etc)', max_length=255, unique=True, verbose_name='name')),
                ('books', models.ManyToManyField(help_text='The books related to the topic', related_name='topics', to='books.book', verbose_name='books')),
            ],
            options={
                'verbose_name': 'topic',
                'verbose_name_plural': 'topics',
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-ref'], name='books_book_ref_1b4a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-created_at'], name='books_book_created_ea3fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-updated_at'], name='books_book_updated_fd0e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-sold_at'], name='books_book_sold_at_0bd8c9_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['price'], name='books_book_price_9cc12f_idx'),
        ),
    ]
