export const CSV_DefaultESPlaceholder = {
  Referencia: null,
  ISBN: null,
  Título: null,
  Autor: null,
  Editorial: null,
  'Lugar de publicación': null,
  'Año de publicación': null,
  colección: null,
  Tamaño: null,
  Peso: null,
  'Número de páginas': null,
  'Estado del libro': null,
  Descripción: null,
  Precio: null,
  Cantidad: null,
  Encuadernación: null,
  'Idioma 1': null,
  'Idioma 2': null,
  Materias: null,
  'Palabras clave': null,
  'Imagen 1 (Principal)': null,
  'Imagen 2': null,
  'Imagen 3': null,
};
